version: "3"
services:
  postgres_test:
    image: postgres
    container_name: postgres_test
    build:
      dockerfile: ./Dockerfile
      context: "."
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dadosjusbr_test
      POSTGRES_PASSWORD: dadosjusbr_test
      POSTGRES_DB: dadosjusbr_test
      POSTGRES_HOST: localhost
