// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo/database/idatabase_repository.go

// Package mock_database is a generated GoMock package.
package database

import (
	reflect "reflect"

	models "github.com/dadosjusbr/storage/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIDatabaseRepository is a mock of IDatabaseRepository interface.
type MockIDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseRepositoryMockRecorder
}

// MockIDatabaseRepositoryMockRecorder is the mock recorder for MockIDatabaseRepository.
type MockIDatabaseRepositoryMockRecorder struct {
	mock *MockIDatabaseRepository
}

// NewMockIDatabaseRepository creates a new mock instance.
func NewMockIDatabaseRepository(ctrl *gomock.Controller) *MockIDatabaseRepository {
	mock := &MockIDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockIDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabaseRepository) EXPECT() *MockIDatabaseRepositoryMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockIDatabaseRepository) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockIDatabaseRepositoryMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIDatabaseRepository)(nil).Connect))
}

// Disconnect mocks base method.
func (m *MockIDatabaseRepository) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockIDatabaseRepositoryMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockIDatabaseRepository)(nil).Disconnect))
}

// GetAgencies mocks base method.
func (m *MockIDatabaseRepository) GetAgencies(uf string) ([]models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgencies", uf)
	ret0, _ := ret[0].([]models.Agency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgencies indicates an expected call of GetAgencies.
func (mr *MockIDatabaseRepositoryMockRecorder) GetAgencies(uf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgencies", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetAgencies), uf)
}

// GetAgenciesCount mocks base method.
func (m *MockIDatabaseRepository) GetAgenciesCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgenciesCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgenciesCount indicates an expected call of GetAgenciesCount.
func (mr *MockIDatabaseRepositoryMockRecorder) GetAgenciesCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgenciesCount", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetAgenciesCount))
}

// GetAgency mocks base method.
func (m *MockIDatabaseRepository) GetAgency(aid string) (*models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgency", aid)
	ret0, _ := ret[0].(*models.Agency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgency indicates an expected call of GetAgency.
func (mr *MockIDatabaseRepositoryMockRecorder) GetAgency(aid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgency", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetAgency), aid)
}

// GetAllAgencies mocks base method.
func (m *MockIDatabaseRepository) GetAllAgencies() ([]models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAgencies")
	ret0, _ := ret[0].([]models.Agency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAgencies indicates an expected call of GetAllAgencies.
func (mr *MockIDatabaseRepositoryMockRecorder) GetAllAgencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAgencies", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetAllAgencies))
}

// GetFirstDateWithMonthlyInfo mocks base method.
func (m *MockIDatabaseRepository) GetFirstDateWithMonthlyInfo() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstDateWithMonthlyInfo")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstDateWithMonthlyInfo indicates an expected call of GetFirstDateWithMonthlyInfo.
func (mr *MockIDatabaseRepositoryMockRecorder) GetFirstDateWithMonthlyInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstDateWithMonthlyInfo", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetFirstDateWithMonthlyInfo))
}

// GetGeneralMonthlyInfo mocks base method.
func (m *MockIDatabaseRepository) GetGeneralMonthlyInfo() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralMonthlyInfo")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralMonthlyInfo indicates an expected call of GetGeneralMonthlyInfo.
func (mr *MockIDatabaseRepositoryMockRecorder) GetGeneralMonthlyInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralMonthlyInfo", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetGeneralMonthlyInfo))
}

// GetGeneralMonthlyInfosFromYear mocks base method.
func (m *MockIDatabaseRepository) GetGeneralMonthlyInfosFromYear(year int) ([]models.GeneralMonthlyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralMonthlyInfosFromYear", year)
	ret0, _ := ret[0].([]models.GeneralMonthlyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralMonthlyInfosFromYear indicates an expected call of GetGeneralMonthlyInfosFromYear.
func (mr *MockIDatabaseRepositoryMockRecorder) GetGeneralMonthlyInfosFromYear(year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralMonthlyInfosFromYear", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetGeneralMonthlyInfosFromYear), year)
}

// GetLastDateWithMonthlyInfo mocks base method.
func (m *MockIDatabaseRepository) GetLastDateWithMonthlyInfo() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastDateWithMonthlyInfo")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastDateWithMonthlyInfo indicates an expected call of GetLastDateWithMonthlyInfo.
func (mr *MockIDatabaseRepositoryMockRecorder) GetLastDateWithMonthlyInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastDateWithMonthlyInfo", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetLastDateWithMonthlyInfo))
}

// GetMonthlyInfo mocks base method.
func (m *MockIDatabaseRepository) GetMonthlyInfo(agencies []models.Agency, year int) (map[string][]models.AgencyMonthlyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyInfo", agencies, year)
	ret0, _ := ret[0].(map[string][]models.AgencyMonthlyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyInfo indicates an expected call of GetMonthlyInfo.
func (mr *MockIDatabaseRepositoryMockRecorder) GetMonthlyInfo(agencies, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyInfo", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetMonthlyInfo), agencies, year)
}

// GetMonthlyInfoSummary mocks base method.
func (m *MockIDatabaseRepository) GetMonthlyInfoSummary(agencies []models.Agency, year int) (map[string][]models.AgencyMonthlyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyInfoSummary", agencies, year)
	ret0, _ := ret[0].(map[string][]models.AgencyMonthlyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyInfoSummary indicates an expected call of GetMonthlyInfoSummary.
func (mr *MockIDatabaseRepositoryMockRecorder) GetMonthlyInfoSummary(agencies, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyInfoSummary", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetMonthlyInfoSummary), agencies, year)
}

// GetNumberOfMonthsCollected mocks base method.
func (m *MockIDatabaseRepository) GetNumberOfMonthsCollected() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumberOfMonthsCollected")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumberOfMonthsCollected indicates an expected call of GetNumberOfMonthsCollected.
func (mr *MockIDatabaseRepositoryMockRecorder) GetNumberOfMonthsCollected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfMonthsCollected", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetNumberOfMonthsCollected))
}

// GetOMA mocks base method.
func (m *MockIDatabaseRepository) GetOMA(month, year int, agency string) (*models.AgencyMonthlyInfo, *models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOMA", month, year, agency)
	ret0, _ := ret[0].(*models.AgencyMonthlyInfo)
	ret1, _ := ret[1].(*models.Agency)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOMA indicates an expected call of GetOMA.
func (mr *MockIDatabaseRepositoryMockRecorder) GetOMA(month, year, agency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOMA", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetOMA), month, year, agency)
}

// GetOPE mocks base method.
func (m *MockIDatabaseRepository) GetOPE(uf string) ([]models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOPE", uf)
	ret0, _ := ret[0].([]models.Agency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOPE indicates an expected call of GetOPE.
func (mr *MockIDatabaseRepositoryMockRecorder) GetOPE(uf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOPE", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetOPE), uf)
}

// GetOPJ mocks base method.
func (m *MockIDatabaseRepository) GetOPJ(group string, year int) ([]models.Agency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOPJ", group, year)
	ret0, _ := ret[0].([]models.Agency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOPJ indicates an expected call of GetOPJ.
func (mr *MockIDatabaseRepositoryMockRecorder) GetOPJ(group, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOPJ", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetOPJ), group, year)
}

// GetPackage mocks base method.
func (m *MockIDatabaseRepository) GetPackage(pkgOpts models.PackageFilterOpts) (*models.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackage", pkgOpts)
	ret0, _ := ret[0].(*models.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackage indicates an expected call of GetPackage.
func (mr *MockIDatabaseRepositoryMockRecorder) GetPackage(pkgOpts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackage", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetPackage), pkgOpts)
}

// GetRemunerationSummary mocks base method.
func (m *MockIDatabaseRepository) GetRemunerationSummary() (*models.RemmunerationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemunerationSummary")
	ret0, _ := ret[0].(*models.RemmunerationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemunerationSummary indicates an expected call of GetRemunerationSummary.
func (mr *MockIDatabaseRepositoryMockRecorder) GetRemunerationSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemunerationSummary", reflect.TypeOf((*MockIDatabaseRepository)(nil).GetRemunerationSummary))
}

// Store mocks base method.
func (m *MockIDatabaseRepository) Store(agmi models.AgencyMonthlyInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", agmi)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIDatabaseRepositoryMockRecorder) Store(agmi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIDatabaseRepository)(nil).Store), agmi)
}

// StorePackage mocks base method.
func (m *MockIDatabaseRepository) StorePackage(newPackage models.Package) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePackage", newPackage)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePackage indicates an expected call of StorePackage.
func (mr *MockIDatabaseRepositoryMockRecorder) StorePackage(newPackage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePackage", reflect.TypeOf((*MockIDatabaseRepository)(nil).StorePackage), newPackage)
}

// StoreRemunerations mocks base method.
func (m *MockIDatabaseRepository) StoreRemunerations(remu models.Remunerations) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRemunerations", remu)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRemunerations indicates an expected call of StoreRemunerations.
func (mr *MockIDatabaseRepositoryMockRecorder) StoreRemunerations(remu interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRemunerations", reflect.TypeOf((*MockIDatabaseRepository)(nil).StoreRemunerations), remu)
}
