# Um dump do banco de dados do dadosjusbr será realizado às 0h de todo dia 17.
name: DUMP

on:
    workflow_dispatch:
    schedule:
        - cron: "0 3 17 * *"
    push:
        branches:
            - 'dump'

jobs:
    Dump:
        runs-on: ubuntu-20.04
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        name: Dump do banco de dados
        steps:
            - uses: actions/checkout@v3

            - name: Conectando ao BD...
              run: |
               psql -h "${{ secrets.POSTGRES_HOST }}" -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}
               echo -e "${{ secrets.POSTGRES_PASSWORD }}\n"
            # - name: Realizando dump...
            #   run: |
            #     POSTGRES_USER="${{ secrets.POSTGRES_USER }}" POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" POSTGRES_DB="${{ secrets.POSTGRES_DB }}" POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}" AWS_REGION="${{ secrets.AWS_REGION }}" S3_BUCKET="${{ secrets.S3_BUCKET }}" go run dump/dump.go