name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19
    services:
      postgres_test:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: dadosjusbr_test
          POSTGRES_PASSWORD: dadosjusbr_test
          POSTGRES_DB: dadosjusbr_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: "apt update && apt install -y postgresql-client"
      - run: "go test --race ./..."
        env:
          POSTGRES_TEST_URL: port=5432 user=dadosjusbr_test dbname=dadosjusbr_test password=dadosjusbr_test sslmode=disable
