name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19
    # services:
    #   postgres_test:
    #     image: postgres
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_USER: dadosjusbr_test
    #       POSTGRES_PASSWORD: dadosjusbr_test
    #       POSTGRES_DB: dadosjusbr_test
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: |
          apt-get update && apt-get install --no-install-recommends -y ca-certificates curl gnupg lsb-release sudo
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update && apt-get install --no-install-recommends -y docker-ce docker-ce-cli containerd.io
      - name: Build Dockerfile
        run: docker build -t dadosjusbr_test repo/database
      - name: Run Dockerfile
        run: |
          docker run -d --name dadosjusbr_test -p 5432:5432 dadosjusbr_test | docker logs dadosjusbr_test
      - run: "go test -v ./..."
        env:
          POSTGRES_CREDENTIALS: postgres://dadosjusbr_test:dadosjusbr_test@postgres_test:5432/dadosjusbr_test?sslmode=disable
