name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19
    services:
      postgres_test:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: dadosjusbr_test
          POSTGRES_PASSWORD: dadosjusbr_test
          POSTGRES_DB: dadosjusbr_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Create Tables
        run: psql -h postgres_test -d dadosjusbr_test -U dadosjusbr_test -f repo/database/init_db.sql'
        env:
          PGPASSWORD: postgres_password
      - run: "go test -v ./..."
        env:
          POSTGRES_CREDENTIALS: postgres://dadosjusbr_test:dadosjusbr_test@postgres_test:5432/dadosjusbr_test?sslmode=disable
